public enum Role
{
    CLERIC, PRIEST, CLERIC_OF_WAR,
    DRUID, SHAMAN, FOREST_DRUID,
    FARMER, REAPER, SEEDER,
    MAGE, VANISHER, BATTLE_MAGE, TOXIN_SPREADER,
    MONK, SHADOW_MONK, MONK_OF_LIFE,
    NECROMANCER, LICH, SPIRIT_NECROMANCER,
    NINJA, ASSASSIN, SABOTAGER,
    PALADIN, HOLY_KNIGHT, GUARDIAN,
    PIRATE, BUCCANEER, CAPTAIN, SWASHBUCKLER,
    RANGER, HUNTER, MARKSMAN,
    ROGUE, THIEF, HIGHWAYMAN,
    SHADOWKNIGHT, PLAGUEKNIGHT, DEATHKNIGHT,
    SORCERER, SWORD_MAGE, ELEMENTAL_SORCEROR,
    WARLOCK, ELDRITCH, OATHBREAKER,
    WARRIOR, BERSERKER, KNIGHT, SAMURAI, LEADER, 
    WIZARD, ELEMENTAL_WIZARD, TIME_WIZARD, ANCIENT_WIZARD;
}
